- alias: Fountain on when Kelly gets home
  trigger:
  - entity_id: group.kelly
    for: 00:01:00
    from: 'not_home'
    platform: state
    to: 'home'
  condition:
  - after: '11:00'
    before: '23:00'
    condition: time
  action:
  - data:
      entity_id: switch.fountain
    service: switch.turn_on


- alias: Verandah Lights on at Sun down
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
  action:
  - service: light.turn_on
    entity_id: group.lights

# Light switch in Man Cave - turn lights on or off
- alias: ManCave Light Switch
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00022c35fd
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.mancave1

# Light switch at front door - turn lights on or off
- alias: Verandah Light Switch
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000228685d
      click_type: single
  action:
  - service: light.toggle
    entity_id: group.lights

# Light switch at front door - Toggle Water Fall
- alias: Waterfall Switch
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000228685d
      click_type: double
  action:
  - data:
      entity_id: switch.fountain
    service: switch.toggle

# Light switch at front door - Toggle Night Mode
- alias: Bedtime Switch
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000228685d
      click_type: hold
  action:
    - service: light.turn_off
      entity_id: light.lamp
    - service: switch.turn_off
      data:
        entity_id: switch.tv_lg
    - service: tts.google_say
      entity_id: media_player.living_room_speaker
      data:
        message: 'Sleep tight'


- alias: Music Switch
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00023d0b83
      click_type: single
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.den
        source: "Walking On Sunshine"
        