- alias: Fountain on when Kelly gets home
  trigger:
  - entity_id: group.kelly
    for: 00:01:00
    from: 'not_home'
    platform: state
    to: 'home'
  condition:
  - after: '11:00'
    before: '23:00'
    condition: time
  action:
  - data:
      entity_id: switch.fountain
    service: switch.toggle

- alias: Verandah Lights on at Sun down
  trigger:
    platform: sun
    event: sunset
  condition:
  action:
  - service: light.toggle
    entity_id: group.lights

- alias: ManCave Light Switch
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00022c35fd
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.mancave1

- alias: Verandah Light Switch
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000228685d
      click_type: single
  action:
  - service: light.toggle
    entity_id: group.lights