
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

discovery:

speedtestdotnet:
  server_id: 2627

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key

#Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api

# lights
#  - platform: lifx
lifx:


# Text to speech
tts:
  - platform: google_translate

zone: !include zones.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
recorder: !include recorder.yaml
sensor: !include sensor.yaml