resources:
  - url: /local/custom_ui/gauge-card.js
    type: js
  - url: /local/custom_ui/light-entity-row.js
    type: js
  - url: /local/custom_ui/bignumber-card.js
    type: js

title: My Lovely Home Automation
views:
  - icon: mdi:home-assistant
    cards:
    - type: weather-forecast
      title: Forcast
      entity: weather.dark_sky
    - type: entities
      title: Weather
      show_header_toggle: true
      entities:
        - sensor.bom_swan_valley_air_temp_c
        - sensor.bom_swan_valley_feels_like_c
        - sensor.bom_swan_valley_rain_today
        - sensor.bom_swan_valley_relative_humidity
        - sensor.bom_swan_valley_wind_direction
        - sensor.bom_swan_valley_wind_gust_kmh
        - sensor.bom_swan_valley_wind_speed_kmh

    - type: entities
      title: People
      show_header_toggle: true
      entities:
          - group.ian
          - group.kelly        

    - type: horizontal-stack
      cards:
      - type: custom:bignumber-card
        title: Ian's Battery
        entity: sensor.life360_ian_battery
        scale: 30px
        from: left
        min: 0
        max: 100
        severity:
          - value: 100
            style: 'var(--label-badge-green)'
          - value: 50
            style: 'var(--label-badge-yellow)'
          - value: 10
            style: 'var(--label-badge-red)'
      - type: custom:bignumber-card
        title: Kelly's Battery
        entity: sensor.life360_kelly_battery
        scale: 30px
        from: left
        min: 0
        max: 100
        severity:
          - value: 100
            style: 'var(--label-badge-green)'
          - value: 50
            style: 'var(--label-badge-yellow)'
          - value: 10
            style: 'var(--label-badge-red)'

    - type: history-graph
      entities:  [sensor.life360_ian_battery, sensor.life360_kelly_battery]
      hours_to_show: 48
      title: Battery History

    - type: horizontal-stack
      cards:
      - type: sensor
        name: Temperature
        entity: sensor.temperature_158d000233fe42
        min: 0
        max: 50

      - type: sensor
        name: Humidity
        entity: sensor.humidity_158d000233fe42
        min: 0
        max: 100


  - title: Lights
    icon: mdi:lightbulb-on
    cards:
      - type: entities
        title: All Lights
        show_header_toggle: true
        entities:
          - group.lights
          - light.lamp
          - light.mancave1
          - light.v1
          - light.v2
          - light.v3
          - light.v4
          - light.v5

  - title: Cams
    icon: mdi:camera
    cards:
      - type: picture-entity
        title: Driveway Cam
        entity: camera.generic_camera
        camera_image: camera.generic_camera
        show_info: true
        tap_action: dialog


  - title: ManCave
    cards:
    - type: glance
      title: Pi Sensors
      entities:
        - sensor.light
        - sensor.pressure
        - sensor.temperature

    - type: entities
      title: Man Cave Light
      entities:
        - type: "custom:light-entity-row"
          entity: light.mancave1
          name: Man Cave Light      # optional

    - type: entities
      title: Mi Light
      entities:
        - type: "custom:light-entity-row"
          entity: light.gateway_light_7c49eb1ce832

    - type: media-control
      entity: media_player.mancave_speaker

    - type: vertical-stack
      cards:
      - type: gauge
        title: Pi CPU 1m
        entity:  sensor.load_1m
        min: 0
        max: 5
        severity:
          red: 5
          green: 0.1
          yellow: 0.5
      - type: horizontal-stack
        cards:
        - type: gauge
          title: Pi CPU 5m
          entity:  sensor.load_5m
          min: 0
          max: 5
          severity:
            red: 5
            green: 0.1
            yellow: 0.5

        - type: gauge
          title: Pi CPU 15m
          entity:  sensor.load_15m
          min: 0
          max: 5
          severity:
            red: 5
            green: 0.1
            yellow: 0.5


  - title: Lounge
    cards:
      - type: entities
        title: Lounge
        show_header_toggle: true
        entities:
          - group.tplink_lounge
          - switch.aircon
          - switch.soundbar
          - switch.tv_lg
          - sensor.tp_link_amps
          - sensor.tp_link_kw
          - sensor.tp_link_volts
          - sensor.tp_link_watts

      - type: entities
        title: Lamp Control
        entities:
          - type: "custom:light-entity-row"
            entity: light.lamp
            icon: mdi:lamp  # optional
            name: Lamp      # optional

      - type: media-control
        entity: media_player.lounge_tv

      - type: horizontal-stack
        cards:
        - type: sensor
          name: Temperature
          entity: sensor.temperature_158d0002322539
          min: 0
          max: 50

        - type: sensor
          name: Temperature
          entity: sensor.humidity_158d0002322539
          min: 0
          max: 100


  - title: Verandah
    cards:
      - type: entities
        title: Verandah - All Devices 
        show_header_toggle: true
        entities:
          - switch.fountain
          - light.v1
          - light.v2
          - light.v3
          - light.v4
          - light.v5

      - type: entities
        title: Fountain Power
        entities:
          - sensor.tp_link_fountain_amps
          - sensor.tp_link_fountain_kw
          - sensor.tp_link_fountain_volts
          - sensor.tp_link_fountain_watts

      - type: entities
        title: Verandah Lights
        entities:
          - type: "custom:light-entity-row"
            entity: group.lights
            icon: mdi:lamp  # optional
            name: Verandah      # optional

      - type: media-control
        entity: media_player.mancave_speaker

