title: My Lovely Home Automation
views:
  - title: Home
    cards:
      - type: picture-entity
        title: Driveway Cam
        entity: camera.generic_camera
        camera_image: camera.generic_camera
        show_info: true
        tap_action: dialog

      - type: media-control
        entity: media_player.chrome

      - type: media-control
        entity: media_player.living_room_speaker

      - type: media-control
        entity: media_player.lounge_tv

      - type: media-control
        entity: media_player.mancave_speaker

      - type: media-control
        entity: media_player.mi_box

      - type: media-control
        entity: media_player.mibox3bedroom

      - type: entity-filter
        title: Device Trackers
        show_header_toggle: true
        entities:
          - device_tracker.life360_ian_franklin
          - device_tracker.life360_kelly_franklin
        state_filter:
          - 'home'
        card:
          type: glance
          title: My Device Trackers


      - type: entities
        title: Groups
        show_header_toggle: true
        entities:
          - group.all_devices
          - group.all_lights
          - group.all_switches
          - group.cameras_menu
          - group.default_view
          - group.envirophat
          - group.ian
          - group.kelly
          - group.lifxlights
          - group.lights
          - group.lights_menu
          - group.media_players
          - group.mediaentities
          - group.people
          - group.power
          - group.tplink_lounge
          - group.weather
          - group.weblinks

      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.lamp
          - light.mancave1
          - light.v1
          - light.v2
          - light.v3
          - light.v4
          - light.v5

      - type: entities
        title: Sensors
        show_header_toggle: true
        entities:
          - sensor.bom_swan_valley_air_temp_c
          - sensor.bom_swan_valley_feels_like_c
          - sensor.bom_swan_valley_rain_today
          - sensor.bom_swan_valley_relative_humidity
          - sensor.bom_swan_valley_wind_direction
          - sensor.bom_swan_valley_wind_gust_kmh
          - sensor.bom_swan_valley_wind_speed_kmh
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
          - sensor.life360_ian_battery
          - sensor.life360_ian_driving
          - sensor.life360_kelly_battery
          - sensor.life360_kelly_driving
          - sensor.light
          - sensor.pressure
          - sensor.sonarr_upcoming
          - sensor.temperature
          - sensor.tp_link_amps
          - sensor.tp_link_kw
          - sensor.tp_link_volts
          - sensor.tp_link_watts
          - sensor.volume_used_volume_1

      - type: entities
        title: Sun
        show_header_toggle: true
        entities:
          - sun.sun

      - type: entities
        title: Switchs
        show_header_toggle: true
        entities:
          - switch.aircon
          - switch.lounge_power
          - switch.soundbar
          - switch.tv_lg

      - type: entities
        title: Weblinks
        show_header_toggle: true
        entities:
          - weblink.ha_graphs
          - weblink.pihole
          - weblink.speedtest_history

      - type: entities
        title: Zones
        show_header_toggle: true
        entities:
          - zone.home
          - zone.ians_work
          - zone.kellys_work